#!/usr/bin/env python3
"""Stage1 opt-in XMM cache acceptance: no privileges, no compiler dependencies.

Usage:
 python3 tools/test_xmm_stage1.py --baseline ./sutram_compiler \\
     --off /tmp/sutram-xmm/off --on /tmp/sutram-xmm/on

The baseline is the last independently verified FG2 compiler. `off` must be
built from the modified source WITHOUT -DSUTRAM_EXPERIMENTAL_XMM_CACHE=1.
`on` is the otherwise identical compiler built WITH that NASM definition.
Checks include exact generated ELF bytes, exact output and status, cache-shape
reuse, and preservation of source evaluation order across control barriers.
This is not a Windows runtime test; perform that on a real Windows host.
"""
from __future__ import annotations
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT=Path(__file__).resolve().parents[1]
START=bytes.fromhex('0f0b66900f0b')
END=bytes.fromhex('0f0b67900f0b')

HOT=r'''mukhya() {
    dasham a = 2.0
    dasham b = 0.5
    dasham c = 1.0
    dasham d = 3.0
    nishkriya("0F 0B 66 90 0F 0B")
    a = a + b
    a = a + b
    a = a + b
    c = a * b
    d = c - b
    nishkriya("0F 0B 67 90 0F 0B")
    likha(a)
    likha(d)
}
'''

def compile_source(compiler, source, output):
    proc=subprocess.run([str(compiler),str(source),str(output)],cwd=ROOT,
      capture_output=True,timeout=50)
    if proc.returncode:
        raise AssertionError(f'compiler {compiler} failed: {proc.stderr.decode(errors="replace")}')
    return output.read_bytes()

def run_elf(path):
    path.chmod(path.stat().st_mode | 0o100)
    x=subprocess.run([str(path)],cwd=ROOT,capture_output=True,timeout=45)
    return x.returncode,x.stdout,x.stderr

def get_slice(binary):
    a=binary.find(START)
    b=binary.find(END,a+len(START))
    if a<0 or b<0: raise AssertionError('missing code markers')
    return binary[a+len(START):b]

def main():
    arg=argparse.ArgumentParser()
    for n in ('baseline','off','on'):
        arg.add_argument('--'+n,required=True,type=Path)
    arg.add_argument('--require-realistic-change',action='store_true')
    args=arg.parse_args()
    for n in ('baseline','off','on'):
        path=getattr(args,n).resolve()
        if not path.is_file(): arg.error(f'compiler not found: {path}')
        setattr(args,n,path)
    nchecks=0
    with tempfile.TemporaryDirectory(prefix='sutram-stage1-') as td:
        temp=Path(td)
        samples=sorted((ROOT/'examples').glob('14[1-8]_*.sm'))
        samples += [ROOT/'examples'/'126_numeric_pipeline.sm']
        if not all(p.is_file() for p in samples):
            raise AssertionError('missing Stage1/Stage2 ABI test or realistic-pipeline example')
        for ix,src in enumerate(samples):
            binaries={}
            results={}
            for name in ('baseline','off','on'):
                output=temp/f'{ix}_{name}.bin'
                binaries[name]=compile_source(getattr(args,name),src,output)
                results[name]=run_elf(output)
            if binaries['baseline']!=binaries['off']:
                raise AssertionError(f'default mode changed generated bytes: {src.name}')
            if results['baseline']!=results['on']:
                raise AssertionError(f'opt-in changed stdout/stderr/exit: {src.name}')
            print(f'PASS default byte identity + opt semantics: {src.name}')
            nchecks+=2
        src=temp/'cache_hot.sm'
        src.write_text(HOT)
        outputs={}
        for name in ('baseline','off','on'):
            outputs[name]=compile_source(getattr(args,name),src,temp/f'{name}_hot.bin')
        if outputs['baseline']!=outputs['off']:
            raise AssertionError('default mode hot-sample bytes changed')
        old=get_slice(outputs['off'])
        new=get_slice(outputs['on'])
        if len(new)>=len(old):
            raise AssertionError(f'opt-in cache did not shrink marked code: {len(old)} -> {len(new)}')
        # The cached SSE operands must be XMM2-5 (not XMM6+). First two loads
        # are allowed, repeat operations should reuse those slots.
        if bytes.fromhex('f20f58') not in new or bytes.fromhex('660f28') not in new:
            raise AssertionError('missing cache arithmetic or XMM copy in optimized code')
        if new.count(bytes.fromhex('f20f58')) < 3:
            raise AssertionError('expected 3 cached addsd instructions')
        objdump=shutil.which('objdump')
        if objdump:
            t=temp/'cached-slice.bin'
            t.write_bytes(new)
            listing=subprocess.run([objdump,'-D','-b','binary','-m','i386:x86-64',
              '-M','intel',str(t)],check=True,capture_output=True,text=True).stdout
            instruction_lines=[line.split('\t')[-1].strip().split(' ')[0] for line in listing.splitlines() if '\t' in line]
            if 'push' in instruction_lines or 'pop' in instruction_lines:
                raise AssertionError('runtime push/pop unexpectedly present in cached hot slice')
            if 'xmm6' in listing or 'xmm7' in listing or 'xmm8' in listing:
                raise AssertionError('Stage1 used XMM6+ (Win64 nonvolatile registers)')
        print(f'PASS XMM2-5 cached code shape: {len(old)} -> {len(new)} bytes')
        nchecks+=1
        pe_off=compile_source(args.off,src,temp/'off_hot.exe')
        pe_on=compile_source(args.on,src,temp/'on_hot.exe')
        if pe_off!=compile_source(args.baseline,src,temp/'baseline_hot.exe'):
            raise AssertionError('default compiled PE differs from previous compiler')
        for image in (pe_off,pe_on):
            if image[:2]!=b'MZ' or b'PE\x00\x00' not in image[:512]:
                raise AssertionError('invalid PE32+ generated header')
        print('PASS default-mode PE byte identity and opt-in PE header validation (not Windows execution)')
        nchecks+=1
        realistic=ROOT/'examples'/'126_numeric_pipeline.sm'
        off=compile_source(args.off,realistic,temp/'off-realistic.bin')
        on=compile_source(args.on,realistic,temp/'on-realistic.bin')
        if off==on:
            print('NOT ACCEPTED FOR DEFAULT: 126 realistic binary unchanged; keep opt-in disabled')
            if args.require_realistic_change: return 2
        else:
            print(f'REALISTIC BINARY DIFFERENCE: sha256 off={hashlib.sha256(off).hexdigest()} '
                  f'on={hashlib.sha256(on).hexdigest()} (timing A/B still required)')
        print(f'PASS {nchecks} functional/cache checks; experimental only')
    return 0

if __name__=='__main__':
    try: sys.exit(main())
    except (AssertionError,subprocess.TimeoutExpired) as exc:
        print('FAIL:',exc,file=sys.stderr)
        sys.exit(1)
